### ISSUE TITLE
Amplitude scaling issues

### ISSUE THREAD

**Issue by varghese-peter** [labstreaminglayer/App-BrainProducts#4]
Hi, I downloaded the LiveAmp application for LabRecorder from ftp://sccn.ucsd.edu/pub/software/LSL/Apps/. It has an issue with the amplitude scaling. However, I see the amplitude scaling issue has been fixed now https://github.com/labstreaminglayer/App-BrainProducts/tree/9b1c646abd85c8bd6fb80b518eacb7819e4fdef3/LiveAmp. How can I implement this in the application, that I can download from the SCCN ftp site? Is there a new LiveAmp app (after v 1.15) with the changes? Any help would be highly appreciated.

**Comment by cboulay** [comment]
I am not familiar with the BrainProducts LSL integrations, but I think what you're looking for can be found on the release page:
https://github.com/labstreaminglayer/App-BrainProducts/releases

Please reopen this issue if it isn't what you're looking for.

**Comment by nmc-costa** [comment]
Hello I reported a similar issue in Actichamp #5 . 
 @varghese-peter did you found the the problem of scaling? 

Thanks for the help.

**Comment by varghese-peter** [comment]
I used the most recent release of the LiveAmp app (LiveAmp-1.16-msvc2015) and it fixed the problem for me.

**Comment by dmedine** [comment]
Yes, the app referenced above (available on the releases page: https://github.com/labstreaminglayer/App-BrainProducts/releases) should work properly.
