### ISSUE TITLE
Error in installing LiveAmp.exe

### ISSUE THREAD

**Issue by goodshawn12** [labstreaminglayer/App-BrainProducts#7]
Dear LSL developer, 

I followed the instruction on [install tutorial](https://github.com/sccn/labstreaminglayer/blob/master/doc/BUILD.md) for building and installing LSL, specifically **LiveAmp** and **LabRecorder**, on my Windows 10 64-bit computer. 

I was able to use "in tree builds'" via Visual Studio 2019 to build and install **liblsl** and **LabRecorder** app (generated a runnable **LabRecorder.exe**). CMake generation was also successful for all the Apps including **LiveAmp**:
`[CMake] -- Installing Components: LabRecorder;LiveAmp;Unspecified;liblsl`

However, when I clicked Build --> Install Lab Streaming Layer, the following error message appeared:
`'../../../Apps/BrainProducts/LiveAmp/LiveAmpLib2.lib', needed by 'Apps/BrainProducts/LiveAmp/LiveAmp.exe', missing and no known rule to make it`

And the error occurred in this line inside LiveAmp/CMakeLists.txt:
https://github.com/labstreaminglayer/App-BrainProducts/blob/f1b319eee02b12c184cb95d55505aab5d65eb687/LiveAmp/CMakeLists.txt#L33

It seems that the file **LiveAmpLib2.lib** was missing. I tried to search online and also in Brain Products tutorial and software packages, but I couldn't find the file (only **LiveAmpLib2.dll**). 

I wonder if I missed any step when installing LiveAmp, or it was indeed a missing file. Any help or insight would be greatly appreciated!

Sincerely,
Shawn

**Comment by dmedine** [comment]
https://github.com/labstreaminglayer/App-BrainProducts/releases

https://github.com/labstreaminglayer/App-LabRecorder/releases

The dll does not ship with the code. Sorry, this is not immediately 
clear. You do not have to build anything, just get the latest release on 
the release page. Same for LabRecorder

**Comment by cboulay** [comment]
I definitely agree with David that you should just use the binary releases if they work for you.

FYI, if you really really want to, it's quite easy to generate the missing .lib file from the .dll. [See this link](http://asawicki.info/news_1420_generating_lib_file_for_dll_library.html) for more info.

**Comment by dmedine** [comment]
By the way: 'Hi, Shawn!'

**Comment by goodshawn12** [comment]
Hi David and Chadwick,
Thanks for the swift reply! I guess I complicated things by trying to build / install the app myself. I totally missed the release package and that is indeed what I need. Appreciate your help!
Just out of curiosity, so is it correct that users won't be able to install LiveAmp themselves because of the missing library (.lib or .dll)? I thought given the source code I should be able to...
Anyway, thanks, Chadwick, for the info!
Best,
Shawn

**Comment by dmedine** [comment]
Yes, that is the way it stands at the moment. I am planning to release a 
new app for both LiveAmp and actiCHamp that will fix all of this. If you 
really want the .lib because you want to make some changes I am happy to 
share it with you. The .dll will be in the C:\Vision\Recorder directory, 
so if you have a LiveAmp, you should at least have that---and (as Chad 
points out) you can reverse engineer the symbols anyway.

**Comment by goodshawn12** [comment]
Got it. The release works perfectly for me so it's good as it is. Thanks again!
